apiVersion: skaffold/v2beta19
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: helm-task
deploy:
  helm:
    releases:
      - name: helm-task
        chartPath: ./deploy/app
        artifactOverrides:
          image: helm-task