apiVersion: skaffold/v2beta19
kind: Config
build:
  artifacts:
    - image: helm-task
      jib:
        type: gradle
deploy:
  helm:
    releases:
      - name: helm-task
        chartPath: ./deploy/helm-task
        skipBuildDependencies: true
portForward:
  - resourceType: deployment
    resourceName: helm-task-deployment
    namespace: default
    port: 8080