spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://helm-task-postgresql:5432/otus
    username: postgres
    password: root

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      status:
        http-mapping:
          - down: 500
          - out_of_service: 503
          - warning: 500
    shutdown:
      enabled: true

