spring:
  main:
    banner-mode: off
  r2dbc:
    url: r2dbc:postgresql://192.168.49.2:32766/otus
    username: postgres
    password: root
    pool:
      enabled: true
      max-idle-time: 1m
  devtools:
    livereload:
      enabled: false
  sql:
    init:
      platform: postgres
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      all: true


logging:
  level:
    org:
      jooq: INFO