spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://192.168.49.2:30843/otus # Dev url, prod comes from ConfigMAp
    username: postgres
    password: root
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      all: true