spring:
  main:
    banner-mode: off
  devtools:
    livereload:
      enabled: false
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/otus
    username: postgres
    password: root
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
    enable:
      all: true

keycloak:
  auth-server-url: http://localhost:8081/auth
  realm: master
  resource: helm-task
  use-resource-role-mappings: true
  bearer-only: true
  credentials:
    secret: d7fc454d-6537-48fc-b122-db402dfe6ca9

logging:
  level:
    org:
      jooq: INFO