apiVersion: v2
name: helm-task
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: postgresql
    version: 10.9.1
    repository: https://charts.bitnami.com/bitnami
#  - name: nginx-ingress-controller
#    version: 7.6.18
#    repository: https://charts.bitnami.com/bitnami