app:
  name: helm-task
  replicas: 1
  container:
    image: tardis5159/helm-task:latest
    port: 8080


global:
  postgresql:
    postgresqlDatabase: otus
    postgresqlUsername: postgres
    postgresqlPassword: root

postgresql:
  image:
    tag: 13