helmTaskApp:
  name: helm-task
  replicas: 1
  port: 8080
  image: tardis5159/helm-task:latest


credentials:
  database:
    name: otus
    uri: jdbc:postgresql://helm-task-postgresql-ha-pgpool:5432/otus
    username: postgres
    password: root


postgresql-ha:
  postgresql:
    database: otus
    username: postgres
    password: root
    repmgrUsername: repmgr
    repmgrPassword: root
    repmgrDatabase: repmgr
#  commonAnnotations:
#    "helm.sh/hook": pre-install

keycloak:
  auth:
    adminUser: admin
    adminPassword: admin


nginx-ingress-controller:
  kind: DaemonSet
  reportNodeInternalIp: true
  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
  service:
    type: NodePort
#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true

#kube-prometheus-stack:
#  prometheus:
#    prometheusSpec:
#      serviceMonitorSelectorNilUsesHelmValues: false
#      serviceMonitorSelector: { }
