helmTaskApp:
  name: helm-task
  replicas: 1
  port: 8080
  image: tardis5159/helm-task:latest


migrations:
  version: V1_1_0


postgresql:
  postgresqlDatabase: otus
  postgresqlUsername: postgres
  postgresqlPassword: root
  commonAnnotations:
    "helm.sh/hook": pre-install


nginx-ingress-controller:
  kind: DaemonSet
  reportNodeInternalIp: true
  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
  service:
    type: NodePort
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: { }
