apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-task-cm
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{.Values.helmTaskApp.name}}-postgresql:5432/{{.Values.postgresql.postgresqlDatabase}}
  SPRING_DATASOURCE_USERNAME: {{.Values.postgresql.postgresqlUsername}}
  SPRING_DATASOURCE_PASSWORD: {{.Values.postgresql.postgresqlPassword}}