apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-task-cm
data:
  SPRING_DATASOURCE_URL: {{.Values.credentials.database.uri}}
  SPRING_DATASOURCE_USERNAME: {{.Values.credentials.database.username}}
  SPRING_DATASOURCE_PASSWORD: {{.Values.credentials.database.password}}