apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job-v1
  annotations:
    "helm.sh/hook": "post-install"
spec:
  template:
    spec:
      containers:
        - name: flyway
          image: flyway/flyway
          args: [ 'migrate' ]
          env:
            - name: FLYWAY_URL
              value: {{.Values.credentials.database.uri}}
            - name: FLYWAY_USER
              value: {{.Values.credentials.database.username}}
            - name: FLYWAY_PASSWORD
              value: {{.Values.credentials.database.password}}
            - name: FLYWAY_DRIVER
              value: org.postgresql.Driver
          envFrom:
            - secretRef:
                name: database-secrets
          volumeMounts:
            - name: config-volume
              mountPath: /flyway/sql
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: migrations-cm