/*
 * This file is generated by jOOQ.
 */
package com.otus.helm.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements Serializable {

    private static final long serialVersionUID = 1L;

    private String   name;
    private String[] permissions;

    public Role() {}

    public Role(Role value) {
        this.name = value.name;
        this.permissions = value.permissions;
    }

    public Role(
        String   name,
        String[] permissions
    ) {
        this.name = name;
        this.permissions = permissions;
    }

    /**
     * Getter for <code>public.role.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.role.name</code>.
     */
    public Role setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.role.permissions</code>.
     */
    public String[] getPermissions() {
        return this.permissions;
    }

    /**
     * Setter for <code>public.role.permissions</code>.
     */
    public Role setPermissions(String[] permissions) {
        this.permissions = permissions;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(name);
        sb.append(", ").append(Arrays.toString(permissions));

        sb.append(")");
        return sb.toString();
    }
}
