/*
 * This file is generated by jOOQ.
 */
package com.otus.helm.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long   id;
    private String login;
    private String password;
    private String name;
    private String role;

    public Users() {}

    public Users(Users value) {
        this.id = value.id;
        this.login = value.login;
        this.password = value.password;
        this.name = value.name;
        this.role = value.role;
    }

    public Users(
        Long   id,
        String login,
        String password,
        String name,
        String role
    ) {
        this.id = id;
        this.login = login;
        this.password = password;
        this.name = name;
        this.role = role;
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.users.id</code>.
     */
    public Users setId(Long id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.users.login</code>.
     */
    public String getLogin() {
        return this.login;
    }

    /**
     * Setter for <code>public.users.login</code>.
     */
    public Users setLogin(String login) {
        this.login = login;
        return this;
    }

    /**
     * Getter for <code>public.users.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.users.password</code>.
     */
    public Users setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>public.users.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.users.name</code>.
     */
    public Users setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.users.role</code>.
     */
    public String getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.users.role</code>.
     */
    public Users setRole(String role) {
        this.role = role;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Users (");

        sb.append(id);
        sb.append(", ").append(login);
        sb.append(", ").append(password);
        sb.append(", ").append(name);
        sb.append(", ").append(role);

        sb.append(")");
        return sb.toString();
    }
}
