/*
 * This file is generated by jOOQ.
 */
package com.otus.helm.enums;


import com.otus.helm.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Permissions implements EnumType {

    USER_UPDATE("USER_UPDATE"),

    USER_READ("USER_READ"),

    USER_DELETE("USER_DELETE");

    private final String literal;

    private Permissions(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "permissions";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
