/*
 * This file is generated by jOOQ.
 */
package com.otus.helm;


import com.otus.helm.tables.Role;
import com.otus.helm.tables.Users;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ROLE_NAME_UINDEX = Internal.createIndex(DSL.name("role_name_uindex"), Role.ROLE, new OrderField[] { Role.ROLE.NAME }, true);
    public static final Index USER_ID_UINDEX = Internal.createIndex(DSL.name("user_id_uindex"), Users.USERS, new OrderField[] { Users.USERS.ID }, true);
    public static final Index USERS_LOGIN_UINDEX = Internal.createIndex(DSL.name("users_login_uindex"), Users.USERS, new OrderField[] { Users.USERS.LOGIN }, true);
}
