/*
 * This file is generated by jOOQ.
 */
package com.otus.helm;


import com.otus.helm.tables.Role;
import com.otus.helm.tables.Users;
import com.otus.helm.tables.records.RoleRecord;
import com.otus.helm.tables.records.UsersRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RoleRecord> ROLE_PK = Internal.createUniqueKey(Role.ROLE, DSL.name("role_pk"), new TableField[] { Role.ROLE.NAME }, true);
    public static final UniqueKey<UsersRecord> USER_PK = Internal.createUniqueKey(Users.USERS, DSL.name("user_pk"), new TableField[] { Users.USERS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UsersRecord, RoleRecord> USERS__USERS_ROLE_NAME_FK = Internal.createForeignKey(Users.USERS, DSL.name("users_role_name_fk"), new TableField[] { Users.USERS.ROLE }, Keys.ROLE_PK, new TableField[] { Role.ROLE.NAME }, true);
}
