/*
 * This file is generated by jOOQ.
 */
package com.otus.helm;


import com.otus.helm.tables.FlywaySchemaHistory;
import com.otus.helm.tables.Role;
import com.otus.helm.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
